CREATE TABLE IF NOT EXISTS todo (
    tno BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    dueDate DATE NOT NULL,
    writer VARCHAR(50) NOT NULL,
    finished BOOLEAN DEFAULT FALSE
);
